### PR TITLE
Fix single source exome/genome values in variant table

### LINKED ISSUE #1639: ACs and ANs don't update in gene page variant table when switching exomes/genomes off and on
For variants with both exome and genome data, when selecting/deselecting exomes or genomes on the gene page, the AC and AN figures in the variant table don't update, but rather continue to show the combined totals for exome and genome.

### PR DESCRIPTION
**Pull request by rileyhgrant**
Resolves #1639 

When the `joint` frequency data was added as a 3rd source of truth for frequency information, the function that merges exome and genome data was modified to preferentially use the `joint` values if they exist. This caused the table to not update AC and AN values when a user de-selected either the exomes or genomes.

This PR passes an additional prop to the merging function to have it only preferentially use the `joint` data when both the exome and genome data are selected by the user. This way, when a source is de-selected, the function falls back to using only the data source selected.

### CODE REVIEW

File: browser/src/VariantList/mergeExomeAndGenomeData.ts [hunk 1]
```diff
@@ -125,14 +125,16 @@ type MergedVariant = Variant & {
 export const mergeExomeAndGenomeData = ({
   datasetId,
   variants,
+  preferJointData = true,
 }: {
   datasetId?: DatasetId
   variants: Variant[]
+  preferJointData?: boolean
```
Comment (phildarnowsky-broad) [inline browser/src/VariantList/mergeExomeAndGenomeData.ts:132]: since you have the default value there you should be able to leave the `?` off

**Review by phildarnowsky-broad — APPROVED** [review]
one minor change noted, good to go once that is done
