### PR TITLE
Fix Gene page "export to CSV" genetic ancestry group data mismatch

### LINKED ISSUE #1307: mismatched v4 variant data between downloaded file and web-displayed info
</style>
</head>

<body link="#0563C1" vlink="#954F72">

16 | 2089662
-- | --

</body>

</html>

* For concerns about data, check the frequently asked questions
  (https://gnomad.broadinstitute.org/help#frequently-asked-questions) or
  send an email to gnomad@broadinstitute.org.

-->

### PR DESCRIPTION
**Pull request by rileyhgrant**
Resolves #1307 

On the gene page there is a button that allows users to export the variant list to a `.csv`. As of v4, the variants in the list can have a differing set of genetic ancestry groups (e.g. some variants may have `AC`, `AN`, etc, for `mid` while others may not, this is because of v4 using v3 for its genomes, and its own values for its genomes).

The gene page combines the genome and exome level data variants in an early processing step, presumably for ease of exporting. It accomplishes this by accessing values based on their position in a list. Now that the exomes and genomes populations can differ in size and order, this export produces a list with incorrect values for v4 variants that occur in both exomes and genomes (e.g. taking `[4]` from genomes is Amish, but `[4]` in exomes is Middle Eastern).

This PR changes the logic to make it more general to fix this bug.

- Removes the assumption that the 0th element of the array's genetic ancestry groups are representative of every element in the array (which is a faulty assumption for v4 variants that are in both exomes and genomes)
- Combines genetic ancestry group values using the `id` field, rather than combining based purely on index

It also adds tests to confirm this behavior.

### CODE REVIEW

File: browser/src/VariantList/ExportVariantsButton.tsx [hunk 1]
```diff
@@ -1,10 +1,79 @@
...
+
+  let populationColumns: Column[] = []
+  datasetPopulations.forEach((popId: PopulationId) => {
+    const popName = GNOMAD_POPULATION_NAMES[popId]
+
+    populationColumns = populationColumns.concat([
+      {
+        label: `Allele Count ${popName}`,
+        getValue: (variant: VariantTableVariant) =>
+          variant.populations.filter((v) => v.id === popId)[0]
```
Comment (phildarnowsky-broad) [inline browser/src/VariantList/ExportVariantsButton.tsx:41]: Looks like the same logic apart from column name in a number of places, let's take this opportunity to extract a helper function to make that clearer.

**Review by phildarnowsky-broad — CHANGES_REQUESTED** [review]

File: browser/src/VariantList/mergeExomeAndGenomeData.spec.ts [hunk 2]
```diff
@@ -0,0 +1,148 @@
...
+
+describe('mergeExomeAndGenomePopulationData', () => {
+  it('returns expected values when exomes and genomes have the same populations', () => {
+    const geneticAncestryGroupObjects = createAncestryGroupObjects([
+      { id: 'afr', value: 1 },
+      { id: 'remaining', value: 2 },
+      { id: 'eur', value: 4 },
+    ])
+
+    const mockVariant = variantFactory.build({
```
[the remark this answers is not in the document]
Comment (rileyhgrant) [reply browser/src/VariantList/mergeExomeAndGenomeData.spec.ts:38]: Ah, interesting, That makes sense!

File: browser/src/VariantList/mergeExomeAndGenomeData.ts [hunk 3]
```diff
@@ -1,6 +1,48 @@
...
+        id: genomePopulation.id,
+        ac: genomePopulation.ac,
+        an: genomePopulation.an,
+        ac_hemi: genomePopulation.ac_hemi,
+        ac_hom: genomePopulation.ac_hom,
+      }
+    }
+  })
+
+  return Object.values(populations).map((population: Population) => population)
```
[the remark this answers is not in the document]
Comment (rileyhgrant) [reply browser/src/VariantList/mergeExomeAndGenomeData.ts:43]: Oops, yeah good call.

File: browser/src/VariantPage/VariantPage.tsx [hunk 4]
```diff
@@ -148,7 +148,7 @@ export type Population = {
   ac_hemi: number | null
   ac_hom: number
   homozygote_count?: number
-  hemizygote_count?: number | null
+  hemizygote_count?: number
```
Comment (phildarnowsky-broad) [inline browser/src/VariantPage/VariantPage.tsx:151]: Ah what I meant here was let's use the `| null` rather than `?` in both counts--that's assuming that we're getting those values directly from GraphQL, if not then never mind.

**Review by phildarnowsky-broad — CHANGES_REQUESTED** [review]
One last small change due to me being unclear earlier

File: browser/src/VariantPage/VariantPage.tsx (hunk 4 above)
Comment (rileyhgrant) [reply browser/src/VariantPage/VariantPage.tsx:151]: Aha, I see, yeah my edit was unclear also. The query for the Variant page doesn't actually request the `hemizygote_count` and `homozygote_count` fields, so I added the `?` to let me Type the populations here without having to add a dummy value for those two. So maybe the true type should actually be `hemizygote_count?: number | null`?

```
populations {
  id
  ac
  an
  ac_hemi
  ac_hom
}
``` 

Digging a little deeper, looks like `ac_hemi` and `ac_hom` are aliased names of `hemizygote_count` and `homozygote_count` that you can query to get the same value. Looks like ClinVar names them `ac_hemi` etc, so it made sense to add the alias in our API at some point in the past to match.

Unsure of what the best thing to do right now is. It feels like it should be safe to remove `hemizygote_count` and `homozygote_count` from this type (and a brief run of tests and typecheck after doing that goes fine), but I also feel like maybe that should be a seperate PR? It feels different in scope than this one, but I can also see the argument that this PR concerns this type and these files.

Comment (rileyhgrant) [reply browser/src/VariantPage/VariantPage.tsx]: Ok nice, that makes sense to me.

Added that commit and going to formally re-request review! I did a force push so the changes since last reviewed might not work, but all the PR review commits are tagged as fixup.

**Review by phildarnowsky-broad — APPROVED** [review]
